//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WijsOef.Data.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class office
    {
        public long id { get; set; }
        public string street { get; set; }
        public string city { get; set; }
        public double latitude { get; set; }
        public double longitude { get; set; }
        public string is_open_in_weekends { get; set; }
        public string has_support_desk { get; set; }
    }
}
